bsmg/wiki

- wiki/mapping/README.md
Added additional remaining content, updated formatting, shuffled some content to its final resting place. Still pending links to mapping practices child pages, working on those next!
> Updates to Mapping home page

- wiki/mapping/mediocre-map-assistant.md
Attempted to fix some formatting, added missing images, completed Basic Controls and Error Checker sections
> Completion of MMA2 User Guide Page

- wiki/pc-modding.md
* Removed BeatDrop from suggested mod installers
* Removed redundant warning message
* Cleaned up the page a bit
> Cleanup PC Modding page

- wiki/about/3d-artists.md
- wiki/about/modders.md
- wiki/about/supports.md
- wiki/pc-modding.md
Updated a few of the pages, most notably moving some information in FAQ to the pc modding guide and updating about pages.
> general updates

- wiki/pc-modding.md
> removed references to beatdrop in the beginner's guide

- package.json
- wiki/.vuepress/config.js
- yarn.lock
- OpenGraph Metadata for all pages
- Names JS chunks based on page content, better for caching
> Build optimisations and improvements

- wiki/mapping/basic-audio.md
Converted to VuePress elements from wiki.js blockquotes and fixed the section ref links.
Also tweaked formatting a bit to look better with the referenced images
> Fix Basic Audio Page

- wiki/mapping/extended-mapping.md
This is a revised version of my first (real) PR, so this is just me adding the "Set-Up" section in the "Extended Mapping" guides.
> Extended Mapping Set-Up

- wiki/mapping/mediocre-map-assistant.md
I was trying to commit these changes to the other PR before merging it.
> Fix image filenames and center align divs

- wiki/mapping/basic-audio.md
https://trello.com/c/YT9oPmO3
https://trello.com/c/Ux1BKHMi
Update formatting for tool assist calculation and info on the click track and recommended sites to source good audio.
> Information Clarification for Basic Audio

- wiki/mapping/README.md
Cleaning up quick start section
Added joke from old wiki
Update more info
Added reference to +1 Rabbit's bs-viewer
https://trello.com/c/Xla8h0in
https://trello.com/c/TudaqEsf
https://trello.com/c/seXkeFIE
> Mapping Home Improvements

- wiki/mapping/extended-mapping.md
Re-formats the MMA2 setup instructions to be more clear and have vuepress formatting
Also adds reference to BeatMapper and ChroMapper and documentation if available
https://trello.com/c/L2nKrUxt
> Content addition and reformatting for ME setup

- wiki/mapping/README.md
- wiki/mapping/basic-audio.md
- wiki/mapping/basic-mapping.md
- wiki/mapping/mediocre-map-assistant.md
Map Home:
- A little more emphasis on no need to upload map
- Add known bug that duplicate map files in both custom level folders would cause unintentional behavior
- Reformat the Beatsaver troubleshooting steps for a cleaner look.
MMA2 Guide:
- Add known bug for auto fill path for steam users
- Emphasis on how permanent the MMA2 delete button is
- Add warning on special characters in map files
Basic Mapping:
- Add warning on special characters in map files
Basic Audio:
- Add download audacity step to the quick start
- Move AV mirror download and Plan your first note section for better flow
> Mapping general update

- wiki/about/3d-artists.md
- wiki/about/modders.md
- wiki/about/moderators.md
- Rugtveit and Pink have been moved from their spots in Modders and 3D Artists to Moderators
- Add placeholder descriptions until they can check back with better ones
- Add/update roles and contributions for the two
- Fix capitalization for ChroMapper because its been bugging me
> Add new members to Moderators list

- wiki/quest-modding.md
- Added a sidebar to the Quest Modding page
- Some minor formatting and style changes
> Quest sidebar

- .gitignore
- package.json
This should fix the sidebar not updating when changes are made to headers that effect the sidebar.
Works in my own dev environment.
Solution taken from this issue https://github.com/vuejs/vuepress/issues/1536
> Hot reload sidebar

- wiki/grips-and-tricks.md
https://ptb.discordapp.com/channels/441805394323439646/674096762633322497/680850435325689913
Make any changes you want.
> Fix hitbox image

- wiki/faq/README.md
> Make a fix to old support page

- wiki/quest-modding.md
Removed BSQI as it hasn't been updated in a while.
> Yeeted old stuffs

- .github/workflows/wiki-update-tracker.yml
This pr just bumps the version of Wiki Update Tracker to v1.4.
**WUP 1.4**
- Fixed additions / deletions counter
Thanks Awagi!
> 📝Bump WUT version to v1.4

- wiki/mapping/extended-mapping.md
Formatting update
Rephrase sentences for clarity
> Spooky patch-1 revision

- wiki/mapping/README.md
- wiki/mapping/basic-audio.md
- wiki/mapping/basic-mapping.md
- wiki/mapping/extended-mapping.md
- wiki/mapping/intermediate-lighting.md
- wiki/mapping/mediocre-map-assistant.md
Basic Audio:
- Adjust source numbering
- Add press spacebar to listen in step 8
Basic Mapping:
- Add gameplay video example of handclaps see https://trello.com/c/Wg658HMG for mirror video in case twitch link goes down
Extended Mapping:
- removed `-` from degrees of counter clockwise rotation
- add left/right parenths for those who don't know clockwise rotations
Intermediate Lighting:
- Update info on flash/fade lighting block behavior
MMA2:
- Various emphasis on need to run the exe from the extracted folder instead of inside the zip
- Clarification on Check WIP path to include enter confirmation
- Revise troubleshooting to mention the blank path or launching from zip could be a cause
- Add more examples of special characters
Mapping Home:
- Migrating from official editor to community …
> Content Update & Official Editor Migration Steps

- wiki/models/custom-sabers.md
> Update custom sabers page

- wiki/about/3d-artists.md
- wiki/about/moderators.md
- wiki/about/supports.md
- wiki/quest-modding.md
> Updated Support section to add Chara_ and RedBrumbler, Fixed layout of Quest troubleshooting, added support to Pink and Red in their about pages

- wiki/README.md
> Fix spelling of bloq

- wiki/models/custom-notes.md
> Finish Custom Notes page

- wiki/fr/README.md
- wiki/fr/about/3d-artists.md
- wiki/fr/about/staff.md
- wiki/fr/mapping/README.md
- wiki/fr/quest-modding.md
- wiki/mapping/README.md
- wiki/quest-modding.md
Updating FR translation according to latest original page update.
Fixed link and typo in README and mapping README.
> :fr: Translation update & fixes

- .github/workflows/wiki.yml
- Dockerfile
* Changes org name
* Optimises build time
> Workflow changes

- wiki/pc-modding.md
> Remove reference to in-game playlist downloads

- wiki/README.md
- wiki/communities/README.md
- wiki/communities/community-hub.md
- wiki/communities/regional-hub.md
I was unable to sync my old PR properly.
This is the same content as before!
> Community hubs

- wiki/communities/README.md
Fixes the broken links that snuck into previous PR
> Fix hub links

- wiki/fr/README.md
- wiki/fr/about/mapping-supports.md
- wiki/fr/about/moderators.md
- wiki/fr/about/staff.md
- wiki/fr/about/supports.md
- wiki/fr/communities/README.md
- wiki/fr/communities/community-hub.md
- wiki/fr/communities/regional-hub.md
- wiki/fr/mapping/README.md
- wiki/fr/modding/README.md
- wiki/fr/models/custom-notes.md
- wiki/fr/pc-modding.md
- wiki/fr/quest-modding.md
- wiki/fr/support/README.md
- wiki/mapping/README.md
- wiki/pc-modding.md
- wiki/quest-modding.md
- wiki/support/README.md
French translation update
French translation init for community hubs
Fixed typos and broken links in some original files
Added a reference to ModAssistant to download playlist in pc-modding
Added a warning in support/README desperate measures about disabling the anti-virus
> French translation update

- wiki/about/mapping-supports.md
- wiki/about/staff.md
- wiki/mapping/basic-lighting.md
- wiki/mapping/mediocre-map-assistant.md
Also condensed tip boxes in mma2 guide stats section
> Update Bloodcloak to Staff, smooth camera break fpfc, mma2 link down

- Dockerfile
- LICENSE
- README.md
- nginx/nginx.conf
- package.json
- wiki/.vuepress/config.js
- wiki/README.md
- wiki/fr/pc-modding.md
- wiki/pc-modding.md
- yarn.lock
> More improvements

- wiki/mapping/README.md
Changed mapping form link
Added .egg error to quest playtesting
> Small mapping page updates

- wiki/mapping/README.md
Pretty sure this one should also be changed.
(From a big PR to this small boi.)
> New MMA2 Link

- package.json
- wiki/.vuepress/config.js
- wiki/.vuepress/enhanceApp.js
- yarn.lock
* Enable smooth scrolling
* Fix anchor URLs in Chrome
> Scrolling Features

- wiki/about/3d-artists.md
- wiki/about/mapping-supports.md
- wiki/about/modders.md
- wiki/about/moderators.md
- wiki/about/staff.md
- wiki/about/supports.md
- wiki/fr/about/3d-artists.md
- wiki/fr/about/mapping-supports.md
- wiki/fr/about/modders.md
- wiki/fr/about/moderators.md
- wiki/fr/about/staff.md
- wiki/fr/about/supports.md
- wiki/fr/mapping/README.md
- wiki/fr/pc-modding.md
- wiki/fr/quest-modding.md
- wiki/fr/support/README.md
- wiki/mapping/README.md
- wiki/mapping/basic-audio.md
- wiki/mapping/basic-mapping.md
- wiki/mapping/intermediate-lighting.md
- wiki/mapping/mapping-anxiety.md
- wiki/mapping/mapping-credits.md
- wiki/mapping/mediocre-map-assistant.md
- wiki/quest-modding.md
- wiki/support/README.md
- wiki/support/new-support.md
* Normalised capitalisation for a bunch of brand names
* Moved myself and Rug from Moderators to Staff
* Moved Rabbit from Modders to Staff
* Sort about pages alphabetically
* Sort `See Also` cards alphabetically (and make them not look like ass)
> Misc Changes

- wiki/.vuepress/config.js
- wiki/README.md
* Added site title to open graph embeds.
* Added example page description for use in embeds.
> [Feature] Meta Tag Optimisation

- wiki/mapping/README.md
- wiki/mapping/basic-lighting.md
- wiki/mapping/extended-mapping.md
Add NPS to testplay format
Add aggressive/soft colors in overrides
Clarify warning with SongCore characteristics
> Minor Changes

- wiki/about/mapping-supports.md
- wiki/about/supports.md
added Bullet and Pyrowarfare to mapping supports
added Johnny to supports
> Role updates

- wiki/mapping/basic-mapping.md
> Half Jump Distance -> Half Jump Duration

- wiki/quest-modding.md
I added a warning about bmbf breaking base game leaderboards, added scoresaber to the useful links section, and removed the unable to enable assets mod troubleshooting section as that bug was fixed on the latest bmbf. i hope i did this right its my first time doing a pr
> Improved quest modding guide a bit 

- wiki/README.md
- wiki/mapping/basic-mapping.md
- wiki/mapping/glossary.md
- wiki/models/README.md
- wiki/models/sabers-guide.md
- Block Distribution in basic mapping
- Fast/Hyper Wall desc correction
- Add patreon to home page
- remove mod history spreadsheet from home page
- remove direct link to models channels on 3d models home page
- add qosmetics to 3d models homepage 
- update custom sabers unity project download
> Gen Update

- wiki/about/modders.md
(I'm Lauriethefish#6700 on discord.)
> Added myself to the modders section.

- wiki/about/modders.md
I think this is a much more accurate description of my current involvement
> Update myself in modders

- wiki/about/modders.md
Sorry for bothering you again. Apparently I can't type.
> Corrected typo (oops)

- wiki/about/modders.md
Basically added myself to the modders section 😸 
It "only" took like... 4 months?
> Add yourself to modders.md any%

- README.md
- wiki/about/staff.md
- wiki/faq/README.md
- wiki/mapping/README.md
- wiki/mapping/mapping-credits.md
- wiki/mapping/mediocre-map-assistant.md
- wiki/models/custom-avatars.md
- wiki/models/custom-notes.md
- wiki/models/custom-platforms.md
- wiki/models/custom-sabers.md
- wiki/models/custom-walls.md
- wiki/quest-modding.md
- wiki/support/README.md
Address more issues raised by translators
Update my own credit
Fix MMA2 controls link in troubleshooting section
> Content Update

- wiki/models/README.md
- wiki/quest-modding.md
some of it didnt look very proper so i tried to fix it, make any changes you want
> Fix minor issues on Quest Modding page

- wiki/mapping/intermediate-mapping.md
Other than in Mapping Glossary there is nothing in the wiki that that discusses inverts. There is a macro in the BSMG explaining it but again, nothing here.
Since I never had any information about them, I was unable to provide proper feedback on them during a testplay the other day that mostly contained inverts. It was only this morning when I was reading though mapping-discussion that I learned what they really are and how they really affected a map.
Most of the information I added is taken directly from the macro in BSMG as well as from people who had the discussion about inverts today.
> Adding information about Inverts

- wiki/faq/README.md
- wiki/grips-and-tricks.md
- wiki/mapping/README.md
- wiki/mapping/basic-mapping.md
- wiki/mapping/glossary.md
- wiki/mapping/map-format.md
- wiki/mapping/mediocre-map-assistant.md
- wiki/models/avatars-guide.md
- wiki/models/notes-guide.md
- wiki/models/platforms-guide.md
- wiki/models/sabers-guide.md
- wiki/pc-modding.md
- wiki/quest-modding.md
- wiki/ranking-guide.md
- wiki/support/README.md
Address personal todo list and the issues brought up by translators
> Misc update

- wiki/quest-modding.md
as the title says, added in the new stuff thats necessary and added some qol of things that makes it much nicer, credit goes to 
Simme63#4202 main writer + dumbass
Eradawn#0368 grammar police + fixed a bunch of issues and made it understandable + a cutie
ComputerElite#0486 fact checker + dumb mistake fixer
Lauriethefish#6700 triple also fact checker + some other small things
rui2015#0303 also fact checker + double checker
Pink#3877 also also fact checker + big cutie
> Updated the quest modding wiki since it was outdated

- wiki/about/modders.md
> Update Auros About Page

- wiki/ranking-guide.md
changed my discord handle recently. updated it in the ranking guide in case people try to reach out.
> updated new discord handle in ranking-guide

- wiki/about/moderators.md
> Updated mod list

- wiki/about/mapping-supports.md
Added myself to the /about/mapping-support area.
> My Mapping Support bio/links

- wiki/mapping/basic-mapping.md
- wiki/mapping/intermediate-mapping.md
Not really sure where to put the Intermediate Parity Video so I just put it there. 
Would like to restructure the Intermediate Mapping page later.
> Parity Short Videos

- wiki/de/models/platforms-guide.md
Fixes the issue noted in #330 for #325
> Updated Platforms guide

- wiki/quest-modding.md
Fixed a few things I stumbled upon while proofreading/translating for the dutch part of the wiki.
Felt like it would be easier/faster to make a commit for it myself directly.
Vast majority of the changes simply involves capitalization of names.
> Minor fixes on the Quest Modding page

- wiki/pc-modding.md
Basically what the title of the PR says 😅
> Fixed BeatSaver capitalization on PC Modding page

- wiki/about/supports.md
yeah thats about it in this PR
> Fill in my bio for supports

- wiki/about/modders.md
- wiki/about/translators.md
Basically what the title implies 😸
> Added some links to myself

- wiki/about/moderators.md
- wiki/about/supports.md
> updated mod list for new moderators

- wiki/mapping/map-format.md
> Fix songTimeOffset description

- wiki/mapping/mediocre-map-assistant.md
I had this issue, and I saw a few people talking about it in the discord. So I figured it couldn't hurt to add to the troubleshooting section here.
definitely this issue:
https://discordapp.com/channels/441805394323439646/443569023951568906/863611286679060480
https://discordapp.com/channels/441805394323439646/443569023951568906/845152754032050197
maybe this issue:
https://discordapp.com/channels/441805394323439646/443569023951568906/804690537709830195
https://discordapp.com/channels/441805394323439646/443569023951568906/829668973191626772
https://discordapp.com/channels/441805394323439646/443569023951568906/864692020207681586
> Add issue to MMA2 troubleshooting section

- wiki/mapping/README.md
- wiki/mapping/basic-lighting.md
- wiki/mapping/extended-mapping.md
- wiki/mapping/glossary.md
Updates to a few different pages that referenced coming soon. Also updated BeatSaver section to reflect post-transfer changes. Please merge on October 1.
> CM Open Beta Prep

- wiki/mapping/basic-mapping.md
Avoiding 90° angles entirely is far too strict.
> Basic mapping update

- wiki/quest-modding.md
For users who are just getting started the wiki should mention which version of Beat Saber is needed. Its definitely out of scope here to walk a user through downgrading but at the very minimum we should mention which version is supported by this guide.
> Mention where to check on beat saber version compatibility

- wiki/mapping/basic-lighting.md
- wiki/mapping/extended-mapping.md
- wiki/models/notes-guide.md
Documents the vanilla FPFC hotkeys and rewords some SiraUtil features as FPFCToggle no longer needs to be enabled
> FPFC SiraUtil section reword

- wiki/mapping/map-format.md
> Address unpublished PR feedback

- wiki/quest-modding.md
Added a link to the Beat Saber Quest Modding Guide - `https://bsqmg.cal117.me/`
> Add link to "Useful Links" on quest-modding.md

- wiki/modding/README.md
A few people have gotten confused. Hopefully this clears things up.
I do eventually plan to merge `bsqmg.cal117.me` into this wiki, but I haven't had the time. I will get onto it though during summer.
> Add warning stating that this page is for PC modding.

- wiki/about/modders.md
All this does is update my bio, so it's more in line with what I'm doing in the community these days
> Cleanup of my profile

- wiki/modding/quest-mod-dev-custom-types.md
This makes it more correct, adds more detail, and provides some reference links.
> Update custom-types information

- wiki/mapping/map-format.md
> Document box group events

- wiki/mapping/map-format.md
> Remove v3 bpm change warning

- wiki/models/custom-sabers.md
Saber Factory isn't on Mod Assistant anymore.
Update the wiki to reflect this.
> Update the custom saber page

- wiki/modding/quest-mod-dev-intro.md
- Added a reference to `Ninja`, the build tool used
- Fixed two minor errors on the example code
> Improve Quest modding guide

- wiki/about/modders.md
- wiki/about/moderators.md
- wiki/about/supports.md
- Moved myself (`rui2015`) from the Supports page to the Moderators page
- Added links to GitHub, Ko-Fi and Paypal
- Added Modder and Moderator roles
- Added `X` to the Supports page
- Added `KodenameKRAK` to the Supports page
> Update About Us pages

- wiki/quest-modding.md
old questmodding link outdated, they don't have a downgrade guide anymore.
was going to post the bslegacy page, but @ComputerElite mentioned its better to link directly to the guide
> quicklink fix, requested by @computerelite

- wiki/models/avatars-guide.md
I'm an idiot who follows old guides, so I figured I should update it here, so if this stops one other person from downloading a non-working version I'll be happy.
> Update Avatar Guide for Unity 2019

- wiki/about/event-winner.md
2022 halloween event plus links for mass downloads of submissions
> 2022 Halloween Event update

- wiki/mapping/map-format.md
Boy do I love single character keys.
> Document 3.2.0 map format

- wiki/about/supports.md
Added myself to the support section. :)
> Add Alteran!

- wiki/about/supports.md
> Add my support thing, only took 6 months

- wiki/about/modders.md
I don't know any German, French, Dutch or Japanese so I couldn't do localisations for the addition.
> Add Millzy

- package-lock.json
- package.json
- wiki/.vitepress/config.ts
totally didn't forget this in the vitepress upgrade
> feat: sitemap

- wiki/about/modders.md
Totally not using the new wave of modders as an excuse to change my own description
> Updated Sirspam's modders description

- wiki/about/modders.md
> Adding myself

- wiki/mapping/basic-mapping.md
- wiki/mapping/downmapping.md
- wiki/mapping/mediocre-map-assistant.md
As one of the current maintainers of the **Beat Saber Map Analysis** spreadsheet, I've spent the last few months building a new dedicated web app to serve as a replacement for the legacy tracker, in an effort to move beyond the original limitations of Google Sheets and make improvements to the general infrastructure, which should hopefully make the tool easier for us and/or future collaborators to maintain and hopefully more useful for mappers and players alike moving forward. 
**Links**:
https://officialmech.github.io/bs-analysis/
https://github.com/officialMECH/bs-analysis
I'll list off some of the more noteworthy features/improvements here:
- **Better Presentation/Interactivity** (table filters/sorting, better charts, etc.)
- **Individual Level Stats** (unfinished atm, will update …
> Update References to New Stat Tracker

- .github/workflows/wiki.yml
- package-lock.json
- package.json
bumps deps and uses an action for markdownlint to enable annotation reporting in PRs
> deps: upgrades

- wiki/modding/quest-mod-dev-intro.md
Since BSQMG repo doesn't exist anymore it's probably worth to link to my account instead.
> Fix credits.

- wiki/mapping/index.md
Original link is dead, updated docs to reflect that and introduced new link to site, which is being actively maintained by me
> Update link to Litemapper

- wiki/about/moderators.md
- wiki/about/supports.md
Moved my supports about us to moderator about us. Also changed the description.
> Moving my supports about us to moderator about us.

- wiki/beginners-guide.md
> Add Quest 3 to PC modding devices

- wiki/quest-modding.md
Adds note about ensuring multiplayer mods are available for the latest version of beat saber before upgrading.
> Note about multiplayer mod version support

- wiki/pc-modding.md
Adds "THIS IS THE RECOMMENDED DOWNGRADER." in BSManager's section in Installers. Also updates the Beta Downgrading steps to include the 1.34.2_legacy option, and fixes a typo in the Downgrading Section (Oculus downgrader to OculusDowngrader)
> Updated steps and other info in PC Modding

- wiki/support/index.md
These are other changes that were not pushed before merging in #617 (original PR).
> Support page updates - FOLLOWUP

- wiki/about/supports.md
> change bio

- wiki/models/custom-platforms.md
remove MA, fix typo (idk if it's a typo but i did it anyways)
> Update custom platforms page

- wiki/faq/index.md
change latest moddable version info, remove BeatList, remove mentions of ModAssistant
> Update PC info of FAQ page

- wiki/models/custom-notes.md
- wiki/models/custom-sabers.md
- wiki/models/custom-walls.md
remove BMBF, denote qsaber, qbloq, qwall filetypes as legacy
> update Quest side of model guides

- wiki/modding/quest-mod-dev-intro.md
- Add Powershell Core and CMake installation instructions
- Add instructions to download ninja and Android NDK via qpm
> Update quest modding intro

- wiki/communities/regional-hub.md
Fixed Italian server link to send to the actual server
> Updated Italian server in regional-hub

- .gitignore
- wiki/mapping/how-to-testplay.md
This page hasn't been updated in a while and there were some additional things that I added to it. The reason I am doing this now is I am looking to start a group/system to recognize and provide testplays better across the community, but that is irrelevant to this change. Hopefully the changes make sense and feel like an improvement to the page.
> Update and improvements to "How to Testplay" page

- wiki/about/moderators.md
- wiki/about/staff.md
staff: add 𝔍𝔢𝔫𝔫𝔦𝔣𝔢𝔯 to the retired section, and add BlueRay
moderators: remove BlueRay and add Cyn
> update staff and moderators
