bsmg/wiki

wiki/mapping/README.md, wiki/mapping/advanced-audio.md, wiki/mapping/basic-audio.md, wiki/mapping/glossary.md
Updated
- Credits to +1 Rabbit at their request
- Expanded toolset available from +1 Rabbit
- Beatmapper Tools Link to latest website
- Noting that the lightmap linked is for the 1.0 format and the 2.0 format version is integrated into MM and MMA2
- Noting at least core mods are needed to see the WIP folder in game for PC
- Playtests leadtime from 24-48 hrs to 1-7 days to better reflect the slower queue clearing
- MMA2 user guide link
Removed
- References to the removed mapping FAQ
=> Updating Info for main mapping page and removing faq refs

wiki/mapping/README.md, wiki/mapping/basic-audio.md, wiki/mapping/basic-lighting.md, wiki/mapping/basic-mapping.md
Lots of small content and formatting changes. 
The commits after the first should detail their changes.
The changes in ad856e4 are
Outlining the interested in making a mapper block better
Moving the more detailed look section for ranked into a tip box
Rephrase the basic lighting desc and added advanced lighting text that is not linked
Expanded lightmap description and nudge to manual lighting
Rephrase the testplay format from "code" to "template"
=> Mapping general content update

wiki/mapping/README.md, wiki/mapping/basic-lighting.md, wiki/mapping/basic-mapping.md, wiki/mapping/mediocre-map-assistant.md
Mapping Home: 
- Update lighting link in quick start
- Move credits to bottom of page
Basic Mapping: 
- Fix link to basic lighting
Basic Lighting: 
- Fix typo in FPFC section incorrectly stating beatsaver instead of beat saber
MMA2 User Guide: 
- Note known bug for wip path not carried over after first time setup 
- Difficulty label being optional with the default behavior noted
- One Saber and No Arrows bug resolutions added
- add common cause of no or long loading from edit menu
=> Cleaning up spelling/broken link and update mma2 troubleshooting

wiki/mapping/README.md, wiki/mapping/advanced-audio.md, wiki/mapping/basic-audio.md, wiki/mapping/basic-lighting.md, wiki/mapping/basic-mapping.md, wiki/mapping/glossary.md, wiki/mapping/mediocre-map-assistant.md
Advanced Audio:
- Move credits to the end
Basic Audio:
- Move Credits to the end
- Add bit on AV needing to use ogg or else audio will be desynced because of how mp3/m4a files are encoded
Basic Lighting:
- renamed and revised environment colors section to be more clear on the process and options available for overriding colors
- Moved credits to the end
Basic Mapping:
- Removed contributors thanks
Glossary: 
- Removed contributors thanks
MMA2 Guide:
- Emphasize needing to unzip the mma2 zip from github to not encounter any issues 
- reformatted troubleshooting section to be more clean
- Add bit on how to get to the lighting menu in editor
- Clarify the first time setup options to more explicitly mention quest
Map Home:
- Revised CM listing to be more clear and easy to update when it …
=> More updates and cleaning to mapping

wiki/mapping/README.md, wiki/mapping/advanced-audio.md, wiki/mapping/basic-mapping.md
Advanced Audio:
- Revised step 6 in Warping with Reaper getting started to point to basic mapping plan first note instead of general adjusting audio
Basic Mapping: 
- Corrected note on bombs that players can still hit them when they pass the player
Map Home: 
- Added Descriptions to the audio editing resources as a summary and match the mapping resources format
=> Minor Content Update

wiki/support/new-support.md
server remodel happened and it renamed the channel to #quest-help
=> Rename quest support channel on WIP support page

.github/CODEOWNERS, .github/workflows/wiki-update-tracker.yml
Changes:
- Added Wiki Update Tracker action
- Added Awagi to CODEOWNERS file for the /fr/ translation of the wiki
Awagi's [Wiki Update Tracker](https://github.com/Awagi/wiki-update-tracker) is a translation tool to keep track of changes to all of the wiki's English files.
**Features**
- Watches all wiki files for changes on master branch
- When an English wiki file is changed, creates a GitHub issue showing the changes
**Problem**
- The action needs permission to read the code and create GitHub issues.
- The default `GITHUB_TOKEN` secret provides unnecessary permissions, like the ability to write GitHub packages.
- The wiki is deployed using GitHub's package system, and we don't want to pass this token to any external apps that would be able to release their own packages.
**Solution**
- …
=> Wiki update tracker action

.github/workflows/wiki-update-tracker.yml
Bump the Wiki Update Tracker to the new version that fixes crashing with filename changes.
Tested on my own test repo.
Thanks to Awagi for updating the bot!
=> 📝Bump WUT release version

wiki/fr/about/mapping-supports.md
This should fix the build error with the missing mapping-supports page.
=> FR mapping supports stub page

.github/workflows/wiki-update-tracker.yml, .github/workflows/wiki.yml, wiki/mapping/README.md, wiki/mapping/extended-mapping.md
Add if conditional to WUT and Wiki CI Deploy Jobs to only run if on bsmg's repo and echos to note that the job was skipped due to not running on the bsmg repo.
I tested it as thoroughly as I could. It should work?
This was done so I could keep the actions running on my fork but not spam my github notifications with failed actions whenever I made a commit. Should be useful for others that forked the wiki.
___
These wiki changes were added as a test to ensure that my modifications to the workflows didn't break anything I couldn't test.
Extended Mapping:
- Modify 360/90 characteristic warning to link relevant practices pages 
- Add same warning to 360/90 section
Map Home:
- Add expired web session as cause for general beatsaver error
=> Update mapping and git workflow actions

.github/workflows/wiki-update-tracker.yml, .github/workflows/wiki.yml
so `1` would not be replaced in the output logs. 
It has been changed to `1ENABLED` as a measure to prevent this from happening in the future
=> Change Enable Secret Keyword

.github/workflows/wiki-update-tracker.yml, wiki/fr/mapping/advanced-audio.md, wiki/fr/mapping/advanced-lighting.md, wiki/fr/mapping/basic-audio.md, wiki/fr/mapping/basic-lighting.md, wiki/fr/mapping/basic-mapping.md, wiki/fr/mapping/extended-mapping.md, wiki/fr/mapping/glossary.md, wiki/fr/mapping/intermediate-lighting.md, wiki/fr/mapping/intermediate-mapping.md, wiki/fr/mapping/mapping-credits.md, wiki/fr/mapping/mediocre-map-assistant.md, wiki/fr/modding/extras.md, wiki/fr/modding/intro.md, wiki/fr/modding/linux.md, wiki/fr/support/new-support.md
I updated the **Wiki Update Tracker Action** to **`v1.5`**, so that it now understand a header in Markdown pages: **`translation-done`**.
Setting a page with this header tells a WUT bot to tag it as "new".
The problem before was that WUT didn't distinguish uninitialized translations and translation updates, so we had issues asking us to update 3 lines in the translation even though the 100-lines page didn't have an initialized. These issues were ambiguous and did not reflect what need to be done.
Now we can simply tell WUT when a translation page is a stub. **To do so, every stub translation pages must now have the header between the 3-dash markers**:
```yaml
---
translation-done: false
---
```
It will also give an accurate overview on finished and unfinished translations (the mapping …
=> New header for translation tracking

wiki/mapping/advanced-audio.md
Simple enough I guess.
As an aside: Shouldn't all the links be `.md#anchor` links instead of `.html#anchor` links?
=> fix link "Audio Preparation: Adding Click Track"

.github/workflows/wiki-update-tracker.yml
The **Wiki Update Tracker** bot can now automatically **create non-existing translation pages**, marking it as stub and requiring an initialization. It will be useful:
- to create the whole structure automatically, when adding new language
- to avoid random 404 on the website when a new original page is created and no translation page in the dedicated language do not exist
The feature can be disabled setting the input **`auto-create`** to **`0`** in the `wiki-update-tracker` workflow. _Merging this PR will enable it._
It **does not** require new permission from its dedicated Github App as it does not use Github API. Instead, it uses git commit and pushes on master, so it's all handled within the workflow.
Note that pushes produced by a job in Github Actions do not trigger jobs again, …
=> :arrow_up: Upgrading WUT

.github/workflows/wiki-update-tracker.yml
The idea was to have images in every translation folders to have it translated when required (if the image contains text or another part to localize), but it's definitely unoptimized and isn't done yet.
=> Don't copy images

wiki/models/custom-sabers.md
Nobody ever uses asset swaps anymore, so linking to the Qosmetics community as a place to get sabers would be helpful for the quest section of this page.
=> Update to add Qosmetics Community instead of BMBF on Custom Sabers page

wiki/mapping/advanced-audio.md, wiki/mapping/basic-audio.md
Edited flow of page. The syncing steps for AV and bpm are in one section and less important steps are under an optional header.
Can move Optional Audio Editing to the Advanced Audio page if it's too much information for Basic Audio.
=> Basic Audio Restructure

wiki/mapping/glossary.md
I noticed that the Mapping Glossary has evolved over time, and the inconsistency between glossary entries has been growing.
I went through every glossary entry ensuring that they followed as-closely-as-possible the standard that I will outline below. By no means is the standard set in stone, so please feel free to challenge any of the standards written or changes that I have made. The overall goal in my perspective is to have a consistent guideline for new terms so we do not run into a situation where the way of writing terms and definitions changes again.
I also corrected any typos or questionable grammar that I encountered, as well as added a few terms that were referenced in the definitions that did not have an entry within the glossary already. I did not change the meaning of any of …
=> Mapping Glossary copy editing for consistency and standardization

wiki/modding/README.md
The documentation page is more useful than the repository itself, as it holds what modders will actually be using.
=> Change BSIPA link to point to the BSIPA docs

wiki/mapping/glossary.md
Danger Dash is a term used in the Basic Mapping page under the "DON'T: Forbidden Patterns" section, but was missing from the Mapping Glossary page.
=> Add 'Danger Dash' entry to Mapping Glossary

wiki/mapping/mapping-credits.md
Cleaned up a few small errors:
1. Checkout -> Check out
2. Links were not on a new line for some of the contributor descriptions. The linter was removing the 2 spaces (i.e. new line) from a few descriptions that passed the character threshold, so the descriptions were formatted to fit properly within the threshold.
3. Reordered the list of contributors to be in proper alphabetical order.
Also, added myself to the list of contributors based on @bloodcloak's recommendation in #315, thank you for the consideration!
=> Copyedited the Mapping Resources Contributors page. Added namaki mono to list of contributors.

wiki/quest-modding.md
I've recently spent hours having issue when modding Beat Saber on my Oculus Quest 2.
It turned out that the [Multi-User experimental feature](https://www.oculus.com/blog/gather-your-party-introducing-multi-user-and-app-sharing-on-oculus-quest/) was causing the BS installer to crash.
After installing you can re-add those accounts and the mods run fine.
=> Warning about Multi-User Oculus feature

wiki/mapping/basic-mapping.md, wiki/mapping/intermediate-mapping.md
Flicks definitely aren't a completely forbidden pattern. Triangles are situational so they also belong there.
I don't believe right triangles don't need their own category. An entry in the glossary should be fine.
Changed "spawn distance" to "jump distance" as that's the more commonly term used now and sliders are faster.
=> Updates to Mapping Pages

wiki/mapping/README.md, wiki/quest-modding.md
On this pull request, I:
- Refactored the Playtesting on a Quest section, to reflect the changes introduced with the new SongLoader
- Changed the location of the SongDownloader mod, because now it is on the Mods panel on the left side, instead of being on the Mod Settings menu.
=> Fix some Quest-related stuff on the wiki

wiki/pc-modding.md
This page says "Beat Saber will NEVER ask you to run it as Administrator. If you've downloaded and installed a mod and you get the User Account Control prompt, DO NOT click accept"
The only issue is that ModAssistant will ask to make changes to your computer, which requires administrator access, when enabling OneClick™ installs.
Even though this is not Beat Saber itself asking for administrator access, I think this still should be mentioned to avoid confusion
=> ModAssistant will ask for administrator access even though the wiki says it shouldn't

wiki/mapping/map-format.md
This has been fixed since at least 1.23.0.
=> Remove mid anchor mode warning

wiki/quest-modding.md
- Update Multiplayer mod installation info
- Update SideQuest instructions to easy installer
- Remove BMBF installation via bmbf.dev in favor of the SideQuest easy installer
- Add BSMG invite on multiple mentions of the discord server
- Add warning to manage save data section saying to isntall the sidequest advanced installer
- Update Core mods list
- Remove Bookmark song installing as that is broken
- Remove Playlist Editor Pro as Darkuni has stepped down from everything quest related
- Remove 3 dots error as that hasn't occurred in a long time. Last time I remember was back in the 1.13.2 days (I also asked X if they remember anyone having the issue)
- Update PC BMBF fix
- Remove ancient issue from before 1.16.4
- Update updating of BMBF to SideQuest instead of bmbf.dev
- Maps now load …
=> Update quest modding guide

wiki/modding/quest-mod-dev-intro.md
The current latest build of templatr (windows, https://github.com/QuestPackageManager/templatr/actions/runs/4088946923) seems to have changed usage. It no longer has a `use` subcommand, and a full git repository path must be provided to it, along with a destination folder.
```
PS> templatr use Lauriethefish/quest-mod-template
error: unexpected argument 'Lauriethefish/quest-mod-template' found
Usage: templatr.exe --git <GIT> <DEST>
For more information, try '--help'.
```
Using the help command returns:
```
PS> templatr --help
Templatr rust rewrite (implementation not based on the old one)
Usage: templatr.exe --git <GIT> <DEST>
Arguments:
<DEST>  Destination where template will be copied to. FILES WILL BE OVERWRITTEN
Options:
-g, --git <GIT>  Link to the git repo, sinonymous with the git …
```
=> Update templatr usage

wiki/modding/quest-mod-dev-intro.md
The link in the templatr example is missing “.git” at the end which causes templatr to not work.
=> Fix git link for templatr 

wiki/.vitepress/theme/custom.css, wiki/.vitepress/theme/index.ts
The original script abused the fact that later elements render over earlier elements without z-index to render the overlay on the top. Moving to vitepress broke this as the new site theme uses z-index. The fix is very straightforward: assign a z-index to the zoom overlay.
Also fixed alongside is contrast problems presented by images with a transparent background, including my own figures. These figures assume a light-colored background in light mode, but unfortunately the dark overlay makes the images difficult to see when zoomed. Changing background color to side background color solves the issue.
Custom styles are moved from inline to custom.css for ease of maintenance.
=> Tweak zoom image on click behavior

wiki/mapping/difficulty-format-v3.md
The v3 format page links to v2 events. However, the link is currently incorrect and nothing happens when you click on it.
This commit updates the link to correctly point to the events section on the v2 format page.
=> Fix broken link to v2 events

wiki/models/sabers-guide.md
this is all i could find but there might be more
=> Update capitalization for sabers guide

.github/workflows/wiki.yml, README.md, wiki/.vitepress/config.ts
When deploying to GitHub Pages on forked repositories, this fix modifies the workflow so that the base configuration can be set automatically via a CLI setting supported by vite and vitepress.
This makes it so that the user does not have to manually configure or revert any commits made to the configuration file directly, and streamlines the process for previewing changes.
take 2 :)
=> Configure deployments via workflow

wiki/de/faq/index.md, wiki/de/quest-modding.md, wiki/fr/faq/index.md, wiki/fr/quest-modding.md, wiki/ja/faq/index.md, wiki/ja/quest-modding.md, wiki/nl/faq/index.md, wiki/nl/quest-modding.md
-  Replaces the old playlist manager app due to the domain (https://beatsaberquest.com) now leading to a scam site, and now direct people to https://github.com/exelix11/QuestSongManager
- Replace BeastSaber playlists link with BeatSaver as BeastSaber no longer has it's own playlists section
- Remove the warning about songs only appearing once, as it is unnecessary now
=> Update playlists sections

wiki/pc-modding.md
Updates the INFO note about the latest moddable version to 1.37, and adds "however, we recommend using 1.34.2."
=> Updated INFO about latest moddable version in PC Modding

wiki/mapping/index.md
In `index.md`, update `sdcard/ModData/com.beatgames.beatsaber/Mods/SongLoader/CustomWIPLevels` to `sdcard/ModData/com.beatgames.beatsaber/Mods/SongCore/CustomWIPLevels`.
I tried the former on my Quest 2 and SongLoader did not work, but SongCore did, at least for ModsBeforeFriday.
This is my first pull request, so I might have made a mistake.
=> Update index.md (https://bsmg.wiki/mapping/#testing-on-a-quest)

wiki/pc-modding.md
Rewrites the latest moddable version to say "The latest Beat Saber version may not be moddable", and adds a link to the modding-announcements channel for the purpose of checking if the latest version is moddable. This is to fix an inconsistency of having to update this every time a Beat Saber update is released.
=> Rewrites latest moddable version note and add 1.37.1 branch in Downgrading

wiki/pc-modding.md
Adds the issues with 1.37.2 to ModAssistant, and add a deprecation notice to BSMM's section, as that is broken as well on 1.37.2 and above.
Preview of these changes are found [here.](https://overlappingd.github.io/bsmg-wiki/pc-modding.html#modassistant)
=> Add 1.37.2 issues to deprecation notice in ModAssistant

wiki/pc-modding.md
add BetterSongSearch, remove anything that mentions ModAssistant apart from the deprecation notice, add BSM to install folders, add link to custom walls install guide, and add note from support page about support roles
=> update PC Modding page

wiki/.vitepress/config/en.ts
With the period in the URL, it causes a 404 Error to occur.
For example, if you are nested at `https://bsmg.wiki/mapping/#additional-mapping-tools`, or even just `https://bsmg.wiki/mapping/`, clicking on the Contact Us will direct you to `https://bsmg.wiki/mapping/contact-us` which doesn't exist.
=> Fixes 404 Error in "Contact Us" URL

wiki/pc-modding.md, wiki/support/index.md
adds back ModAssistant as a reliable mod installer
removes deprecation notices
=> add back ModAssistant

wiki/de/mapping/basic-audio.md, wiki/mapping/basic-audio.md
Some time ago I created a website that tries to take all the work out of syncing audio for mapping. I made the project for fun and to test my dev skills. Since then people loved it and some are using it regularly for new maps. For the future I also plan on adding audio normalization so that BeatTimer takes away step 4 aswell (see changes). *(Edit: Volume Normalization was added)*
The application works completely locally using ffmpeg-wasm so no login or hosting is needed on my part. It would be a shame if people don't know about it and lose the time benefit. Or for some installing Audacity could also be a challenge stopping them from mapping (audio-synced maps). So I propose to add that tip into the docs and would be happy if the work helps more people out there.
This is the repo of the …
=> Add tip for using BeatTimer in basic audio mapping guides
